# coding: utf-8

"""
    RIME Rest API

    API methods for RIME. Must be authenticated with `rime-api-key` header.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: dev@robustintelligence.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ModelModelInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'path_info': 'ModelPathModelInfo',
        'loader_info': 'ModelLoaderModelInfo',
        'hugging_face_info': 'ModelHuggingFaceModelInfo'
    }

    attribute_map = {
        'path_info': 'pathInfo',
        'loader_info': 'loaderInfo',
        'hugging_face_info': 'huggingFaceInfo'
    }

    def __init__(self, path_info=None, loader_info=None, hugging_face_info=None):  # noqa: E501
        """ModelModelInfo - a model defined in Swagger"""  # noqa: E501
        self._path_info = None
        self._loader_info = None
        self._hugging_face_info = None
        self.discriminator = None
        if path_info is not None:
            self.path_info = path_info
        if loader_info is not None:
            self.loader_info = loader_info
        if hugging_face_info is not None:
            self.hugging_face_info = hugging_face_info

    @property
    def path_info(self):
        """Gets the path_info of this ModelModelInfo.  # noqa: E501


        :return: The path_info of this ModelModelInfo.  # noqa: E501
        :rtype: ModelPathModelInfo
        """
        return self._path_info

    @path_info.setter
    def path_info(self, path_info):
        """Sets the path_info of this ModelModelInfo.


        :param path_info: The path_info of this ModelModelInfo.  # noqa: E501
        :type: ModelPathModelInfo
        """

        self._path_info = path_info

    @property
    def loader_info(self):
        """Gets the loader_info of this ModelModelInfo.  # noqa: E501


        :return: The loader_info of this ModelModelInfo.  # noqa: E501
        :rtype: ModelLoaderModelInfo
        """
        return self._loader_info

    @loader_info.setter
    def loader_info(self, loader_info):
        """Sets the loader_info of this ModelModelInfo.


        :param loader_info: The loader_info of this ModelModelInfo.  # noqa: E501
        :type: ModelLoaderModelInfo
        """

        self._loader_info = loader_info

    @property
    def hugging_face_info(self):
        """Gets the hugging_face_info of this ModelModelInfo.  # noqa: E501


        :return: The hugging_face_info of this ModelModelInfo.  # noqa: E501
        :rtype: ModelHuggingFaceModelInfo
        """
        return self._hugging_face_info

    @hugging_face_info.setter
    def hugging_face_info(self, hugging_face_info):
        """Sets the hugging_face_info of this ModelModelInfo.


        :param hugging_face_info: The hugging_face_info of this ModelModelInfo.  # noqa: E501
        :type: ModelHuggingFaceModelInfo
        """

        self._hugging_face_info = hugging_face_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModelModelInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelModelInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
