# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dynatrace/odin/proto/collector/trace/v1/dynatrace_envelopes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dynatrace/odin/proto/collector/trace/v1/dynatrace_envelopes.proto',
  package='dynatrace.odin.proto.collector.trace.v1',
  syntax='proto3',
  serialized_options=_b('\n+com.dynatrace.odin.proto.collector.trace.v1B\022DynatraceEnvelopesH\001Z8dynatrace.com/odin/odin-proto/gen/go/collector/traces/v1'),
  serialized_pb=_b('\nAdynatrace/odin/proto/collector/trace/v1/dynatrace_envelopes.proto\x12\'dynatrace.odin.proto.collector.trace.v1\"1\n\x13\x43lusterTimeResponse\x12\x1a\n\x12\x63lusterTimestampMs\x18\x01 \x01(\x06\x42}\n+com.dynatrace.odin.proto.collector.trace.v1B\x12\x44ynatraceEnvelopesH\x01Z8dynatrace.com/odin/odin-proto/gen/go/collector/traces/v1b\x06proto3')
)




_CLUSTERTIMERESPONSE = _descriptor.Descriptor(
  name='ClusterTimeResponse',
  full_name='dynatrace.odin.proto.collector.trace.v1.ClusterTimeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clusterTimestampMs', full_name='dynatrace.odin.proto.collector.trace.v1.ClusterTimeResponse.clusterTimestampMs', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['ClusterTimeResponse'] = _CLUSTERTIMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClusterTimeResponse = _reflection.GeneratedProtocolMessageType('ClusterTimeResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLUSTERTIMERESPONSE,
  '__module__' : 'dynatrace.odin.proto.collector.trace.v1.dynatrace_envelopes_pb2'
  # @@protoc_insertion_point(class_scope:dynatrace.odin.proto.collector.trace.v1.ClusterTimeResponse)
  })
_sym_db.RegisterMessage(ClusterTimeResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
