"""
    ELEMENTS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elements_sdk
from elements_sdk.model.veritone_job_list import VeritoneJobList


class TestVeritoneJobList(unittest.TestCase):
    """VeritoneJobList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVeritoneJobList(self):
        """Test VeritoneJobList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VeritoneJobList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
