# coding: utf-8

"""
    ELEMENTS API

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import elements_sdk
from elements_sdk.models.one_time_access_token import OneTimeAccessToken  # noqa: E501
from elements_sdk.rest import ApiException

class TestOneTimeAccessToken(unittest.TestCase):
    """OneTimeAccessToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test OneTimeAccessToken
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = elements_sdk.models.one_time_access_token.OneTimeAccessToken()  # noqa: E501
        if include_optional :
            return OneTimeAccessToken(
                id = 56, 
                activity = [
                    elements_sdk.models.one_time_access_token_activity.OneTimeAccessTokenActivity(
                        id = 56, 
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        ip = '0', 
                        token = 56, )
                    ], 
                user = elements_sdk.models.elements_user_mini_reference.ElementsUserMiniReference(
                    id = 56, 
                    avatar = '0', 
                    display_name = '0', 
                    email = '0', 
                    full_name = '0', 
                    is_external = True, 
                    is_cloud = True, 
                    username = '0', ), 
                created_by = elements_sdk.models.elements_user_mini.ElementsUserMini(
                    id = 56, 
                    avatar = '0', 
                    display_name = '0', 
                    email = '0', 
                    full_name = '0', 
                    is_external = True, 
                    is_cloud = True, 
                    username = '0', ), 
                media_root_permissions = '0', 
                shared_bundles = [
                    elements_sdk.models.one_time_access_token_shared_object.OneTimeAccessTokenSharedObject(
                        id = 56, 
                        name = '0', )
                    ], 
                shared_directories = [
                    elements_sdk.models.one_time_access_token_shared_object.OneTimeAccessTokenSharedObject(
                        id = 56, 
                        name = '0', )
                    ], 
                full_url = '0', 
                url = '0', 
                token = '0', 
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                view_limit_enabled = True, 
                view_limit_left = -2147483648, 
                expires = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                require_login = True, 
                is_easy_sharing_for_bundle = 56, 
                is_easy_sharing_for_directory = 56
            )
        else :
            return OneTimeAccessToken(
                user = elements_sdk.models.elements_user_mini_reference.ElementsUserMiniReference(
                    id = 56, 
                    avatar = '0', 
                    display_name = '0', 
                    email = '0', 
                    full_name = '0', 
                    is_external = True, 
                    is_cloud = True, 
                    username = '0', ),
                url = '0',
                token = '0',
        )

    def testOneTimeAccessToken(self):
        """Test OneTimeAccessToken"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
