# coding: utf-8

"""
    ELEMENTS API

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import elements_sdk
from elements_sdk.models.inline_response2001 import InlineResponse2001  # noqa: E501
from elements_sdk.rest import ApiException

class TestInlineResponse2001(unittest.TestCase):
    """InlineResponse2001 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse2001
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = elements_sdk.models.inline_response2001.InlineResponse2001()  # noqa: E501
        if include_optional :
            return InlineResponse2001(
                count = 56, 
                next = '0', 
                previous = '0', 
                results = [
                    elements_sdk.models.click_gallery_link.ClickGalleryLink(
                        id = 56, 
                        email = '0', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        gallery_id = 56, 
                        notify_on_use = True, 
                        views_left = 56, 
                        elements_user = elements_sdk.models.click_link_user.ClickLinkUser(
                            id = '0', 
                            username = '0', 
                            email = '0', 
                            display_name = '0', ), 
                        secret_key = '0', )
                    ]
            )
        else :
            return InlineResponse2001(
                count = 56,
                results = [
                    elements_sdk.models.click_gallery_link.ClickGalleryLink(
                        id = 56, 
                        email = '0', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        gallery_id = 56, 
                        notify_on_use = True, 
                        views_left = 56, 
                        elements_user = elements_sdk.models.click_link_user.ClickLinkUser(
                            id = '0', 
                            username = '0', 
                            email = '0', 
                            display_name = '0', ), 
                        secret_key = '0', )
                    ],
        )

    def testInlineResponse2001(self):
        """Test InlineResponse2001"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
