"""
    ELEMENTS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import elements_sdk
from elements_sdk.model.veritone_engine_list import VeritoneEngineList


class TestVeritoneEngineList(unittest.TestCase):
    """VeritoneEngineList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVeritoneEngineList(self):
        """Test VeritoneEngineList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VeritoneEngineList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
