# coding: utf-8

"""
    ELEMENTS API

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import elements_sdk
from elements_sdk.models.register_upload_metadata_endpoint_request import RegisterUploadMetadataEndpointRequest  # noqa: E501
from elements_sdk.rest import ApiException

class TestRegisterUploadMetadataEndpointRequest(unittest.TestCase):
    """RegisterUploadMetadataEndpointRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RegisterUploadMetadataEndpointRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = elements_sdk.models.register_upload_metadata_endpoint_request.RegisterUploadMetadataEndpointRequest()  # noqa: E501
        if include_optional :
            return RegisterUploadMetadataEndpointRequest(
                items = [
                    elements_sdk.models.metadata_item.MetadataItem(
                        custom_fields = {
                            'key' : '0'
                            }, 
                        tags = [
                            {
                                'key' : '0'
                                }
                            ], 
                        path = '0', )
                    ]
            )
        else :
            return RegisterUploadMetadataEndpointRequest(
                items = [
                    elements_sdk.models.metadata_item.MetadataItem(
                        custom_fields = {
                            'key' : '0'
                            }, 
                        tags = [
                            {
                                'key' : '0'
                                }
                            ], 
                        path = '0', )
                    ],
        )

    def testRegisterUploadMetadataEndpointRequest(self):
        """Test RegisterUploadMetadataEndpointRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
