# coding: utf-8

"""
    ELEMENTS API

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import elements_sdk
from elements_sdk.models.trace_node import TraceNode  # noqa: E501
from elements_sdk.rest import ApiException

class TestTraceNode(unittest.TestCase):
    """TraceNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TraceNode
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = elements_sdk.models.trace_node.TraceNode()  # noqa: E501
        if include_optional :
            return TraceNode(
                children = [
                    elements_sdk.models.recursive_field.RecursiveField()
                    ], 
                name = '0', 
                r = 56, 
                w = 56, 
                total_children = 56
            )
        else :
            return TraceNode(
                children = [
                    elements_sdk.models.recursive_field.RecursiveField()
                    ],
                name = '0',
        )

    def testTraceNode(self):
        """Test TraceNode"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
