# coding: utf-8

"""
    ELEMENTS API

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import elements_sdk
from elements_sdk.models.tag_media_directory_request import TagMediaDirectoryRequest  # noqa: E501
from elements_sdk.rest import ApiException

class TestTagMediaDirectoryRequest(unittest.TestCase):
    """TagMediaDirectoryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TagMediaDirectoryRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = elements_sdk.models.tag_media_directory_request.TagMediaDirectoryRequest()  # noqa: E501
        if include_optional :
            return TagMediaDirectoryRequest(
                tag = 56, 
                add = True
            )
        else :
            return TagMediaDirectoryRequest(
                tag = 56,
                add = True,
        )

    def testTagMediaDirectoryRequest(self):
        """Test TagMediaDirectoryRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
