# coding: utf-8

"""
    ELEMENTS API

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import elements_sdk
from elements_sdk.models.search_endpoint_response import SearchEndpointResponse  # noqa: E501
from elements_sdk.rest import ApiException

class TestSearchEndpointResponse(unittest.TestCase):
    """SearchEndpointResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SearchEndpointResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = elements_sdk.models.search_endpoint_response.SearchEndpointResponse()  # noqa: E501
        if include_optional :
            return SearchEndpointResponse(
                tapes = [
                    elements_sdk.models.tape.Tape(
                        id = 56, 
                        root_entry = 56, 
                        name = '0', 
                        uuid = '0', 
                        generation = -2147483648, 
                        custom_a = '0', 
                        custom_b = '0', 
                        custom_c = '0', 
                        custom_d = '0', 
                        free_space = -9223372036854776000, 
                        load_counter = -9223372036854776000, 
                        error_counter = -9223372036854776000, 
                        error_reason = '0', 
                        active = True, 
                        lto = '5', 
                        group = 56, )
                    ], 
                entries = [
                    elements_sdk.models.tape_file.TapeFile(
                        id = 56, 
                        tape = elements_sdk.models.tape.Tape(
                            id = 56, 
                            root_entry = 56, 
                            name = '0', 
                            uuid = '0', 
                            generation = -2147483648, 
                            custom_a = '0', 
                            custom_b = '0', 
                            custom_c = '0', 
                            custom_d = '0', 
                            free_space = -9223372036854776000, 
                            load_counter = -9223372036854776000, 
                            error_counter = -9223372036854776000, 
                            error_reason = '0', 
                            active = True, 
                            lto = '5', 
                            group = 56, ), 
                        path = '0', 
                        search_highlight = '0', 
                        uid = -2147483648, 
                        name = '0', 
                        is_dir = True, 
                        read_only = True, 
                        length = -9223372036854776000, 
                        checksum = '0', 
                        fullpath = '0', 
                        parent = 56, )
                    ], 
                total = 56
            )
        else :
            return SearchEndpointResponse(
                tapes = [
                    elements_sdk.models.tape.Tape(
                        id = 56, 
                        root_entry = 56, 
                        name = '0', 
                        uuid = '0', 
                        generation = -2147483648, 
                        custom_a = '0', 
                        custom_b = '0', 
                        custom_c = '0', 
                        custom_d = '0', 
                        free_space = -9223372036854776000, 
                        load_counter = -9223372036854776000, 
                        error_counter = -9223372036854776000, 
                        error_reason = '0', 
                        active = True, 
                        lto = '5', 
                        group = 56, )
                    ],
                entries = [
                    elements_sdk.models.tape_file.TapeFile(
                        id = 56, 
                        tape = elements_sdk.models.tape.Tape(
                            id = 56, 
                            root_entry = 56, 
                            name = '0', 
                            uuid = '0', 
                            generation = -2147483648, 
                            custom_a = '0', 
                            custom_b = '0', 
                            custom_c = '0', 
                            custom_d = '0', 
                            free_space = -9223372036854776000, 
                            load_counter = -9223372036854776000, 
                            error_counter = -9223372036854776000, 
                            error_reason = '0', 
                            active = True, 
                            lto = '5', 
                            group = 56, ), 
                        path = '0', 
                        search_highlight = '0', 
                        uid = -2147483648, 
                        name = '0', 
                        is_dir = True, 
                        read_only = True, 
                        length = -9223372036854776000, 
                        checksum = '0', 
                        fullpath = '0', 
                        parent = 56, )
                    ],
                total = 56,
        )

    def testSearchEndpointResponse(self):
        """Test SearchEndpointResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
