# coding: utf-8

"""
    ELEMENTS API

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import elements_sdk
from elements_sdk.models.client_session import ClientSession  # noqa: E501
from elements_sdk.rest import ApiException

class TestClientSession(unittest.TestCase):
    """ClientSession unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ClientSession
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = elements_sdk.models.client_session.ClientSession()  # noqa: E501
        if include_optional :
            return ClientSession(
                id = 56, 
                user = elements_sdk.models.elements_user_mini.ElementsUserMini(
                    id = 56, 
                    avatar = '0', 
                    display_name = '0', 
                    email = '0', 
                    full_name = '0', 
                    is_external = True, 
                    is_cloud = True, 
                    username = '0', ), 
                mounted_workspaces = '0', 
                started = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                workstation = elements_sdk.models.workstation_mini.WorkstationMini(
                    id = '0', 
                    display_name = '0', 
                    hostname = '0', )
            )
        else :
            return ClientSession(
                user = elements_sdk.models.elements_user_mini.ElementsUserMini(
                    id = 56, 
                    avatar = '0', 
                    display_name = '0', 
                    email = '0', 
                    full_name = '0', 
                    is_external = True, 
                    is_cloud = True, 
                    username = '0', ),
                workstation = elements_sdk.models.workstation_mini.WorkstationMini(
                    id = '0', 
                    display_name = '0', 
                    hostname = '0', ),
        )

    def testClientSession(self):
        """Test ClientSession"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
