
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-23T14:42:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e9a0cad442cf514cd32ab828fd5b795ba1267922",
 "version": "1.18.0.post0.dev40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
