
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-24T04:26:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ee6f243a7f4669440e267cbe54d5a5f4136b5de4",
 "version": "1.18.0.post0.dev45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
