
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-23T22:31:54+1300",
 "dirty": false,
 "error": null,
 "full-revisionid": "d78a021488eec81afdbda96f0c5a9ffe49fe62ea",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
