# Generated by Django 4.1.5 on 2023-01-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0167_module_status'),
        ('portmanager', '0005_alter_changelog_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='device',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.device'),
        ),
    ]
