# Generated by Django 4.1.5 on 2023-01-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portmanager', '0007_remove_devicegroup_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='interface',
            field=models.CharField(default='', editable=False, max_length=80),
        ),
    ]
