VERSION_YEAR = 2023
VERSION_MONTH = int('01')
VERSION_DAY = int('24')
VERSION_HOUR = int('14')
VERSION_MINUTE = int('51')
MAJOR_VERSION = 1
MINOR_VERSION = 11
PATCH_VERSION = 202301241451
version_date = '2023/01/24 14:51'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
