
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-24T15:10:24-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd2847473a2fe8e52a25782ede1848f4824db538",
 "version": "0.2.61.post0.dev46"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
