
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-20T18:33:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e9609c678301fda9c3ac64487c15468c4291cb09",
 "version": "v23.02.00a230123"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
