
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-20T15:33:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "02429540168cb255f25f403b3311f190eb97b67d",
 "version": "2023.1rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
