"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _simplevalue_types:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _simplevalue_typesEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_simplevalue_types.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    FLOAT_TYPE: _simplevalue_types.ValueType  # 0
    INT_TYPE: _simplevalue_types.ValueType  # 1
    UNSIGNED_TYPE: _simplevalue_types.ValueType  # 2
    BOOL_TYPE: _simplevalue_types.ValueType  # 3
    STRING_TYPE: _simplevalue_types.ValueType  # 4
    VOID_TYPE: _simplevalue_types.ValueType  # 5
    DATETIME_TYPE: _simplevalue_types.ValueType  # 6
    """0.3.0 new types"""

class simplevalue_types(_simplevalue_types, metaclass=_simplevalue_typesEnumTypeWrapper): ...

FLOAT_TYPE: simplevalue_types.ValueType  # 0
INT_TYPE: simplevalue_types.ValueType  # 1
UNSIGNED_TYPE: simplevalue_types.ValueType  # 2
BOOL_TYPE: simplevalue_types.ValueType  # 3
STRING_TYPE: simplevalue_types.ValueType  # 4
VOID_TYPE: simplevalue_types.ValueType  # 5
DATETIME_TYPE: simplevalue_types.ValueType  # 6
"""0.3.0 new types"""
global___simplevalue_types = simplevalue_types

class _byte_data_types:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _byte_data_typesEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_byte_data_types.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UCHAR_TYPE: _byte_data_types.ValueType  # 0
    CHAR_TYPE: _byte_data_types.ValueType  # 1
    USHORT_TYPE: _byte_data_types.ValueType  # 2
    UINT_TYPE: _byte_data_types.ValueType  # 3
    ULONG_TYPE: _byte_data_types.ValueType  # 4
    SHORT_TYPE: _byte_data_types.ValueType  # 5
    IINT_TYPE: _byte_data_types.ValueType  # 6
    LONG_TYPE: _byte_data_types.ValueType  # 7
    BFLOAT_TYPE: _byte_data_types.ValueType  # 8
    BDOUBLE_TYPE: _byte_data_types.ValueType  # 9
    BCOMPLEX_TYPE: _byte_data_types.ValueType  # 11
    """0.3.0 new types"""
    BDATETIME_TYPE: _byte_data_types.ValueType  # 12
    BOPAQUE_TYPE: _byte_data_types.ValueType  # 13

class byte_data_types(_byte_data_types, metaclass=_byte_data_typesEnumTypeWrapper): ...

UCHAR_TYPE: byte_data_types.ValueType  # 0
CHAR_TYPE: byte_data_types.ValueType  # 1
USHORT_TYPE: byte_data_types.ValueType  # 2
UINT_TYPE: byte_data_types.ValueType  # 3
ULONG_TYPE: byte_data_types.ValueType  # 4
SHORT_TYPE: byte_data_types.ValueType  # 5
IINT_TYPE: byte_data_types.ValueType  # 6
LONG_TYPE: byte_data_types.ValueType  # 7
BFLOAT_TYPE: byte_data_types.ValueType  # 8
BDOUBLE_TYPE: byte_data_types.ValueType  # 9
BCOMPLEX_TYPE: byte_data_types.ValueType  # 11
"""0.3.0 new types"""
BDATETIME_TYPE: byte_data_types.ValueType  # 12
BOPAQUE_TYPE: byte_data_types.ValueType  # 13
global___byte_data_types = byte_data_types

class _variant_types:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _variant_typesEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_variant_types.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SIMPLEVAR_TYPE: _variant_types.ValueType  # 0
    STRUCT_TYPE: _variant_types.ValueType  # 1
    ENUM_TYPE: _variant_types.ValueType  # 2
    TUPLE_TYPE: _variant_types.ValueType  # 3
    HOMOG_ARRAY_TYPE: _variant_types.ValueType  # 4

class variant_types(_variant_types, metaclass=_variant_typesEnumTypeWrapper): ...

SIMPLEVAR_TYPE: variant_types.ValueType  # 0
STRUCT_TYPE: variant_types.ValueType  # 1
ENUM_TYPE: variant_types.ValueType  # 2
TUPLE_TYPE: variant_types.ValueType  # 3
HOMOG_ARRAY_TYPE: variant_types.ValueType  # 4
global___variant_types = variant_types

@typing_extensions.final
class empty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___empty = empty

@typing_extensions.final
class variant_descriptor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VARIANT_TYPE_FIELD_NUMBER: builtins.int
    SIMPLEVALUE_TYPE_FIELD_NUMBER: builtins.int
    SIMPLEVALUE_SIZEOF_FIELD_NUMBER: builtins.int
    STRUCT_DESC_FIELD_NUMBER: builtins.int
    ENUM_DESC_FIELD_NUMBER: builtins.int
    TUPLE_DESC_FIELD_NUMBER: builtins.int
    HOMOG_ARRAY_DESC_FIELD_NUMBER: builtins.int
    CPP_TYPE_NAME_FIELD_NUMBER: builtins.int
    variant_type: global___variant_types.ValueType
    simplevalue_type: global___simplevalue_types.ValueType
    simplevalue_sizeof: builtins.int
    @property
    def struct_desc(self) -> global___struct_descriptor: ...
    @property
    def enum_desc(self) -> global___enum_descriptor: ...
    @property
    def tuple_desc(self) -> global___tuple_descriptor: ...
    @property
    def homog_array_desc(self) -> global___homog_array_descriptor: ...
    cpp_type_name: builtins.str
    """new in 0.3.0"""
    def __init__(
        self,
        *,
        variant_type: global___variant_types.ValueType = ...,
        simplevalue_type: global___simplevalue_types.ValueType = ...,
        simplevalue_sizeof: builtins.int = ...,
        struct_desc: global___struct_descriptor | None = ...,
        enum_desc: global___enum_descriptor | None = ...,
        tuple_desc: global___tuple_descriptor | None = ...,
        homog_array_desc: global___homog_array_descriptor | None = ...,
        cpp_type_name: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["enum_desc", b"enum_desc", "homog_array_desc", b"homog_array_desc", "struct_desc", b"struct_desc", "tuple_desc", b"tuple_desc"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["cpp_type_name", b"cpp_type_name", "enum_desc", b"enum_desc", "homog_array_desc", b"homog_array_desc", "simplevalue_sizeof", b"simplevalue_sizeof", "simplevalue_type", b"simplevalue_type", "struct_desc", b"struct_desc", "tuple_desc", b"tuple_desc", "variant_type", b"variant_type"]) -> None: ...

global___variant_descriptor = variant_descriptor

@typing_extensions.final
class struct_descriptor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class StructMapEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___variant_descriptor: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___variant_descriptor | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    STRUCT_NAME_FIELD_NUMBER: builtins.int
    STRUCT_MAP_FIELD_NUMBER: builtins.int
    struct_name: builtins.str
    @property
    def struct_map(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___variant_descriptor]: ...
    def __init__(
        self,
        *,
        struct_name: builtins.str = ...,
        struct_map: collections.abc.Mapping[builtins.str, global___variant_descriptor] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["struct_map", b"struct_map", "struct_name", b"struct_name"]) -> None: ...

global___struct_descriptor = struct_descriptor

@typing_extensions.final
class enum_descriptor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class EnumMapEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.int
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    ENUM_NAME_FIELD_NUMBER: builtins.int
    ENUM_MAP_FIELD_NUMBER: builtins.int
    enum_name: builtins.str
    @property
    def enum_map(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.int]: ...
    def __init__(
        self,
        *,
        enum_name: builtins.str = ...,
        enum_map: collections.abc.Mapping[builtins.str, builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["enum_map", b"enum_map", "enum_name", b"enum_name"]) -> None: ...

global___enum_descriptor = enum_descriptor

@typing_extensions.final
class tuple_descriptor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TUPLE_MAP_FIELD_NUMBER: builtins.int
    @property
    def tuple_map(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___variant_descriptor]: ...
    def __init__(
        self,
        *,
        tuple_map: collections.abc.Iterable[global___variant_descriptor] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["tuple_map", b"tuple_map"]) -> None: ...

global___tuple_descriptor = tuple_descriptor

@typing_extensions.final
class homog_array_descriptor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IS_SIMPLE_FIELD_NUMBER: builtins.int
    IS_ENCODED_FIELD_NUMBER: builtins.int
    HAS_FIXED_SIZE_FIELD_NUMBER: builtins.int
    FIXED_SIZE_FIELD_NUMBER: builtins.int
    VALTYPE_FIELD_NUMBER: builtins.int
    COMPLEX_VALUE_TYPE_FIELD_NUMBER: builtins.int
    is_simple: builtins.bool
    is_encoded: builtins.bool
    has_fixed_size: builtins.bool
    fixed_size: builtins.int
    valtype: global___simplevalue_types.ValueType
    @property
    def complex_value_type(self) -> global___variant_descriptor: ...
    def __init__(
        self,
        *,
        is_simple: builtins.bool = ...,
        is_encoded: builtins.bool = ...,
        has_fixed_size: builtins.bool = ...,
        fixed_size: builtins.int = ...,
        valtype: global___simplevalue_types.ValueType = ...,
        complex_value_type: global___variant_descriptor | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["complex_value_type", b"complex_value_type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["complex_value_type", b"complex_value_type", "fixed_size", b"fixed_size", "has_fixed_size", b"has_fixed_size", "is_encoded", b"is_encoded", "is_simple", b"is_simple", "valtype", b"valtype"]) -> None: ...

global___homog_array_descriptor = homog_array_descriptor

@typing_extensions.final
class ft_variant(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIMPLEVAR_FIELD_NUMBER: builtins.int
    STRUCTVAL_FIELD_NUMBER: builtins.int
    ENUMVAL_FIELD_NUMBER: builtins.int
    TUPLEVAL_FIELD_NUMBER: builtins.int
    ARRAYVAL_FIELD_NUMBER: builtins.int
    @property
    def simplevar(self) -> global___ft_simplevariant: ...
    @property
    def structval(self) -> global___ft_struct: ...
    @property
    def enumval(self) -> global___ft_enum: ...
    @property
    def tupleval(self) -> global___ft_tuple: ...
    @property
    def arrayval(self) -> global___ft_homog_array:
        """0.3.0 new types"""
    def __init__(
        self,
        *,
        simplevar: global___ft_simplevariant | None = ...,
        structval: global___ft_struct | None = ...,
        enumval: global___ft_enum | None = ...,
        tupleval: global___ft_tuple | None = ...,
        arrayval: global___ft_homog_array | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["arrayval", b"arrayval", "enumval", b"enumval", "simplevar", b"simplevar", "structval", b"structval", "tupleval", b"tupleval", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["arrayval", b"arrayval", "enumval", b"enumval", "simplevar", b"simplevar", "structval", b"structval", "tupleval", b"tupleval", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["value", b"value"]) -> typing_extensions.Literal["simplevar", "structval", "enumval", "tupleval", "arrayval"] | None: ...

global___ft_variant = ft_variant

@typing_extensions.final
class ft_simplevariant(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DBLVAL_FIELD_NUMBER: builtins.int
    INTVAL_FIELD_NUMBER: builtins.int
    UINTVAL_FIELD_NUMBER: builtins.int
    BOOLVAL_FIELD_NUMBER: builtins.int
    STRINGVAL_FIELD_NUMBER: builtins.int
    TSTAMPVAL_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    IS_VOID_FIELD_NUMBER: builtins.int
    dblval: builtins.float
    intval: builtins.int
    uintval: builtins.int
    boolval: builtins.bool
    stringval: builtins.str
    @property
    def tstampval(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    size: builtins.int
    is_void: builtins.bool
    def __init__(
        self,
        *,
        dblval: builtins.float = ...,
        intval: builtins.int = ...,
        uintval: builtins.int = ...,
        boolval: builtins.bool = ...,
        stringval: builtins.str = ...,
        tstampval: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        size: builtins.int = ...,
        is_void: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["boolval", b"boolval", "dblval", b"dblval", "intval", b"intval", "stringval", b"stringval", "tstampval", b"tstampval", "uintval", b"uintval", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["boolval", b"boolval", "dblval", b"dblval", "intval", b"intval", "is_void", b"is_void", "size", b"size", "stringval", b"stringval", "tstampval", b"tstampval", "uintval", b"uintval", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["value", b"value"]) -> typing_extensions.Literal["dblval", "intval", "uintval", "boolval", "stringval", "tstampval"] | None: ...

global___ft_simplevariant = ft_simplevariant

@typing_extensions.final
class ft_struct(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class ValueEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___ft_variant: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___ft_variant | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    STRUCT_NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    struct_name: builtins.str
    @property
    def value(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___ft_variant]: ...
    def __init__(
        self,
        *,
        struct_name: builtins.str = ...,
        value: collections.abc.Mapping[builtins.str, global___ft_variant] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["struct_name", b"struct_name", "value", b"value"]) -> None: ...

global___ft_struct = ft_struct

@typing_extensions.final
class ft_enum(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DESC_FIELD_NUMBER: builtins.int
    ENUM_VALUE_FIELD_NUMBER: builtins.int
    @property
    def desc(self) -> global___enum_descriptor: ...
    enum_value: builtins.int
    def __init__(
        self,
        *,
        desc: global___enum_descriptor | None = ...,
        enum_value: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["desc", b"desc"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["desc", b"desc", "enum_value", b"enum_value"]) -> None: ...

global___ft_enum = ft_enum

@typing_extensions.final
class ft_tuple(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    @property
    def value(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ft_variant]: ...
    def __init__(
        self,
        *,
        value: collections.abc.Iterable[global___ft_variant] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["value", b"value"]) -> None: ...

global___ft_tuple = ft_tuple

@typing_extensions.final
class ft_homog_array(google.protobuf.message.Message):
    """new in 0.3.0"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ARR_DECODED_FIELD_NUMBER: builtins.int
    ARR_ENCODED_FIELD_NUMBER: builtins.int
    @property
    def arr_decoded(self) -> global___ft_homog_array_decoded: ...
    @property
    def arr_encoded(self) -> global___ft_homog_array_encoded: ...
    def __init__(
        self,
        *,
        arr_decoded: global___ft_homog_array_decoded | None = ...,
        arr_encoded: global___ft_homog_array_encoded | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["arr_decoded", b"arr_decoded", "arr_encoded", b"arr_encoded", "array", b"array"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["arr_decoded", b"arr_decoded", "arr_encoded", b"arr_encoded", "array", b"array"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["array", b"array"]) -> typing_extensions.Literal["arr_decoded", "arr_encoded"] | None: ...

global___ft_homog_array = ft_homog_array

@typing_extensions.final
class ft_homog_array_encoded(google.protobuf.message.Message):
    """new in 0.3.0"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DTP_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    dtp: global___byte_data_types.ValueType
    data: builtins.bytes
    def __init__(
        self,
        *,
        dtp: global___byte_data_types.ValueType = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "dtp", b"dtp"]) -> None: ...

global___ft_homog_array_encoded = ft_homog_array_encoded

@typing_extensions.final
class ft_homog_array_decoded(google.protobuf.message.Message):
    """new in 0.3.0"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ARR_UINT8_FIELD_NUMBER: builtins.int
    ARR_UINT16_FIELD_NUMBER: builtins.int
    ARR_SINT16_FIELD_NUMBER: builtins.int
    ARR_UINT32_FIELD_NUMBER: builtins.int
    ARR_SINT32_FIELD_NUMBER: builtins.int
    ARR_UINT64_FIELD_NUMBER: builtins.int
    ARR_SINT64_FIELD_NUMBER: builtins.int
    ARR_FLOAT_FIELD_NUMBER: builtins.int
    ARR_DOUBLE_FIELD_NUMBER: builtins.int
    @property
    def arr_uint8(self) -> global___ft_uint8_arr: ...
    @property
    def arr_uint16(self) -> global___ft_uint32_arr:
        """NOTE there is no 16-bit native protobuf type"""
    @property
    def arr_sint16(self) -> global___ft_sint32_arr: ...
    @property
    def arr_uint32(self) -> global___ft_uint32_arr: ...
    @property
    def arr_sint32(self) -> global___ft_sint32_arr: ...
    @property
    def arr_uint64(self) -> global___ft_uint64_arr: ...
    @property
    def arr_sint64(self) -> global___ft_sint64_arr: ...
    @property
    def arr_float(self) -> global___ft_float_arr: ...
    @property
    def arr_double(self) -> global___ft_double_arr: ...
    def __init__(
        self,
        *,
        arr_uint8: global___ft_uint8_arr | None = ...,
        arr_uint16: global___ft_uint32_arr | None = ...,
        arr_sint16: global___ft_sint32_arr | None = ...,
        arr_uint32: global___ft_uint32_arr | None = ...,
        arr_sint32: global___ft_sint32_arr | None = ...,
        arr_uint64: global___ft_uint64_arr | None = ...,
        arr_sint64: global___ft_sint64_arr | None = ...,
        arr_float: global___ft_float_arr | None = ...,
        arr_double: global___ft_double_arr | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["arr_double", b"arr_double", "arr_float", b"arr_float", "arr_sint16", b"arr_sint16", "arr_sint32", b"arr_sint32", "arr_sint64", b"arr_sint64", "arr_uint16", b"arr_uint16", "arr_uint32", b"arr_uint32", "arr_uint64", b"arr_uint64", "arr_uint8", b"arr_uint8", "array", b"array"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["arr_double", b"arr_double", "arr_float", b"arr_float", "arr_sint16", b"arr_sint16", "arr_sint32", b"arr_sint32", "arr_sint64", b"arr_sint64", "arr_uint16", b"arr_uint16", "arr_uint32", b"arr_uint32", "arr_uint64", b"arr_uint64", "arr_uint8", b"arr_uint8", "array", b"array"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["array", b"array"]) -> typing_extensions.Literal["arr_uint8", "arr_uint16", "arr_sint16", "arr_uint32", "arr_sint32", "arr_uint64", "arr_sint64", "arr_float", "arr_double"] | None: ...

global___ft_homog_array_decoded = ft_homog_array_decoded

@typing_extensions.final
class ft_uint8_arr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___ft_uint8_arr = ft_uint8_arr

@typing_extensions.final
class ft_uint16_arr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """note no native 16 bit protobuf types"""
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___ft_uint16_arr = ft_uint16_arr

@typing_extensions.final
class ft_sint16_arr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___ft_sint16_arr = ft_sint16_arr

@typing_extensions.final
class ft_uint32_arr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___ft_uint32_arr = ft_uint32_arr

@typing_extensions.final
class ft_sint32_arr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___ft_sint32_arr = ft_sint32_arr

@typing_extensions.final
class ft_uint64_arr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___ft_uint64_arr = ft_uint64_arr

@typing_extensions.final
class ft_sint64_arr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___ft_sint64_arr = ft_sint64_arr

@typing_extensions.final
class ft_float_arr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___ft_float_arr = ft_float_arr

@typing_extensions.final
class ft_double_arr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values", b"values"]) -> None: ...

global___ft_double_arr = ft_double_arr
