
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-23T14:19:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a69a17e8b188a85c014efd1f7cae356173e3f995",
 "version": "1.18.0.post0.dev38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
