
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-25T19:23:08-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9e2ec22abaa74491d3d1fa5b7ce6636d5c270cf",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
