# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oauth_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13oauth_service.proto"D\n\x1aGetProviderLoginURLRequest\x12\x10\n\x08provider\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x61llback_url\x18\x02 \x01(\t"?\n\x1bGetProviderLoginURLResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x13\n\x0bstate_token\x18\x02 \x01(\t"Q\n\x11OAuthLoginRequest\x12\x10\n\x08provider\x18\x01 \x01(\t\x12\x15\n\rprovider_code\x18\x02 \x01(\t\x12\x13\n\x0bstate_token\x18\x03 \x01(\t"i\n\x12OAuthLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x12\n\nexpires_in\x18\x03 \x01(\t\x12\x12\n\ntoken_type\x18\x04 \x01(\t"c\n#GetProviderLoginURLForAttachRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x10\n\x08provider\x18\x02 \x01(\t\x12\x14\n\x0c\x63\x61llback_url\x18\x03 \x01(\t"H\n$GetProviderLoginURLForAttachResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x13\n\x0bstate_token\x18\x02 \x01(\t"p\n\x1a\x41ttachAccountToUserRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x10\n\x08provider\x18\x02 \x01(\t\x12\x15\n\rprovider_code\x18\x03 \x01(\t\x12\x13\n\x0bstate_token\x18\x04 \x01(\t"\x1d\n\x1b\x41ttachAccountToUserResponse"F\n\x1c\x44\x65tachAccountFromUserRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x10\n\x08provider\x18\x02 \x01(\t"\x1f\n\x1d\x44\x65tachAccountFromUserResponse2\xa2\x03\n\x05OAuth\x12P\n\x13GetProviderLoginURL\x12\x1b.GetProviderLoginURLRequest\x1a\x1c.GetProviderLoginURLResponse\x12\x30\n\x05Login\x12\x12.OAuthLoginRequest\x1a\x13.OAuthLoginResponse\x12k\n\x1cGetProviderLoginURLForAttach\x12$.GetProviderLoginURLForAttachRequest\x1a%.GetProviderLoginURLForAttachResponse\x12P\n\x13\x41ttachAccountToUser\x12\x1b.AttachAccountToUserRequest\x1a\x1c.AttachAccountToUserResponse\x12V\n\x15\x44\x65tachAccountFromUser\x12\x1d.DetachAccountFromUserRequest\x1a\x1e.DetachAccountFromUserResponseb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "oauth_service_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS is False:

    DESCRIPTOR._options = None
    _GETPROVIDERLOGINURLREQUEST._serialized_start = 23
    _GETPROVIDERLOGINURLREQUEST._serialized_end = 91
    _GETPROVIDERLOGINURLRESPONSE._serialized_start = 93
    _GETPROVIDERLOGINURLRESPONSE._serialized_end = 156
    _OAUTHLOGINREQUEST._serialized_start = 158
    _OAUTHLOGINREQUEST._serialized_end = 239
    _OAUTHLOGINRESPONSE._serialized_start = 241
    _OAUTHLOGINRESPONSE._serialized_end = 346
    _GETPROVIDERLOGINURLFORATTACHREQUEST._serialized_start = 348
    _GETPROVIDERLOGINURLFORATTACHREQUEST._serialized_end = 447
    _GETPROVIDERLOGINURLFORATTACHRESPONSE._serialized_start = 449
    _GETPROVIDERLOGINURLFORATTACHRESPONSE._serialized_end = 521
    _ATTACHACCOUNTTOUSERREQUEST._serialized_start = 523
    _ATTACHACCOUNTTOUSERREQUEST._serialized_end = 635
    _ATTACHACCOUNTTOUSERRESPONSE._serialized_start = 637
    _ATTACHACCOUNTTOUSERRESPONSE._serialized_end = 666
    _DETACHACCOUNTFROMUSERREQUEST._serialized_start = 668
    _DETACHACCOUNTFROMUSERREQUEST._serialized_end = 738
    _DETACHACCOUNTFROMUSERRESPONSE._serialized_start = 740
    _DETACHACCOUNTFROMUSERRESPONSE._serialized_end = 771
    _OAUTH._serialized_start = 774
    _OAUTH._serialized_end = 1192
# @@protoc_insertion_point(module_scope)
