# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dynatrace/odin/proto/trace/v1/trace_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dynatrace/odin/proto/trace/v1/trace_config.proto',
  package='dynatrace.odin.proto.trace.v1',
  syntax='proto3',
  serialized_options=_b('\n!com.dynatrace.odin.proto.trace.v1B\020TraceConfigProtoP\001Z-dynatrace.com/odin/odin-proto/gen/go/trace/v1'),
  serialized_pb=_b('\n0dynatrace/odin/proto/trace/v1/trace_config.proto\x12\x1d\x64ynatrace.odin.proto.trace.v1\"\xcb\x03\n\x0bTraceConfig\x12J\n\x10\x63onstant_sampler\x18\x01 \x01(\x0b\x32..dynatrace.odin.proto.trace.v1.ConstantSamplerH\x00\x12P\n\x13probability_sampler\x18\x02 \x01(\x0b\x32\x31.dynatrace.odin.proto.trace.v1.ProbabilitySamplerH\x00\x12S\n\x15rate_limiting_sampler\x18\x03 \x01(\x0b\x32\x32.dynatrace.odin.proto.trace.v1.RateLimitingSamplerH\x00\x12 \n\x18max_number_of_attributes\x18\x04 \x01(\x03\x12\"\n\x1amax_number_of_timed_events\x18\x05 \x01(\x03\x12\x30\n(max_number_of_attributes_per_timed_event\x18\x06 \x01(\x03\x12\x1b\n\x13max_number_of_links\x18\x07 \x01(\x03\x12)\n!max_number_of_attributes_per_link\x18\x08 \x01(\x03\x42\t\n\x07sampler\"\xaa\x01\n\x0f\x43onstantSampler\x12Q\n\x08\x64\x65\x63ision\x18\x01 \x01(\x0e\x32?.dynatrace.odin.proto.trace.v1.ConstantSampler.ConstantDecision\"D\n\x10\x43onstantDecision\x12\x0e\n\nALWAYS_OFF\x10\x00\x12\r\n\tALWAYS_ON\x10\x01\x12\x11\n\rALWAYS_PARENT\x10\x02\"1\n\x12ProbabilitySampler\x12\x1b\n\x13samplingProbability\x18\x01 \x01(\x01\"\"\n\x13RateLimitingSampler\x12\x0b\n\x03qps\x18\x01 \x01(\x03\x42\x66\n!com.dynatrace.odin.proto.trace.v1B\x10TraceConfigProtoP\x01Z-dynatrace.com/odin/odin-proto/gen/go/trace/v1b\x06proto3')
)



_CONSTANTSAMPLER_CONSTANTDECISION = _descriptor.EnumDescriptor(
  name='ConstantDecision',
  full_name='dynatrace.odin.proto.trace.v1.ConstantSampler.ConstantDecision',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALWAYS_OFF', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALWAYS_ON', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALWAYS_PARENT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=648,
  serialized_end=716,
)
_sym_db.RegisterEnumDescriptor(_CONSTANTSAMPLER_CONSTANTDECISION)


_TRACECONFIG = _descriptor.Descriptor(
  name='TraceConfig',
  full_name='dynatrace.odin.proto.trace.v1.TraceConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='constant_sampler', full_name='dynatrace.odin.proto.trace.v1.TraceConfig.constant_sampler', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='probability_sampler', full_name='dynatrace.odin.proto.trace.v1.TraceConfig.probability_sampler', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rate_limiting_sampler', full_name='dynatrace.odin.proto.trace.v1.TraceConfig.rate_limiting_sampler', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_number_of_attributes', full_name='dynatrace.odin.proto.trace.v1.TraceConfig.max_number_of_attributes', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_number_of_timed_events', full_name='dynatrace.odin.proto.trace.v1.TraceConfig.max_number_of_timed_events', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_number_of_attributes_per_timed_event', full_name='dynatrace.odin.proto.trace.v1.TraceConfig.max_number_of_attributes_per_timed_event', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_number_of_links', full_name='dynatrace.odin.proto.trace.v1.TraceConfig.max_number_of_links', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_number_of_attributes_per_link', full_name='dynatrace.odin.proto.trace.v1.TraceConfig.max_number_of_attributes_per_link', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sampler', full_name='dynatrace.odin.proto.trace.v1.TraceConfig.sampler',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=84,
  serialized_end=543,
)


_CONSTANTSAMPLER = _descriptor.Descriptor(
  name='ConstantSampler',
  full_name='dynatrace.odin.proto.trace.v1.ConstantSampler',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='decision', full_name='dynatrace.odin.proto.trace.v1.ConstantSampler.decision', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONSTANTSAMPLER_CONSTANTDECISION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=546,
  serialized_end=716,
)


_PROBABILITYSAMPLER = _descriptor.Descriptor(
  name='ProbabilitySampler',
  full_name='dynatrace.odin.proto.trace.v1.ProbabilitySampler',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='samplingProbability', full_name='dynatrace.odin.proto.trace.v1.ProbabilitySampler.samplingProbability', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=718,
  serialized_end=767,
)


_RATELIMITINGSAMPLER = _descriptor.Descriptor(
  name='RateLimitingSampler',
  full_name='dynatrace.odin.proto.trace.v1.RateLimitingSampler',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='qps', full_name='dynatrace.odin.proto.trace.v1.RateLimitingSampler.qps', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=769,
  serialized_end=803,
)

_TRACECONFIG.fields_by_name['constant_sampler'].message_type = _CONSTANTSAMPLER
_TRACECONFIG.fields_by_name['probability_sampler'].message_type = _PROBABILITYSAMPLER
_TRACECONFIG.fields_by_name['rate_limiting_sampler'].message_type = _RATELIMITINGSAMPLER
_TRACECONFIG.oneofs_by_name['sampler'].fields.append(
  _TRACECONFIG.fields_by_name['constant_sampler'])
_TRACECONFIG.fields_by_name['constant_sampler'].containing_oneof = _TRACECONFIG.oneofs_by_name['sampler']
_TRACECONFIG.oneofs_by_name['sampler'].fields.append(
  _TRACECONFIG.fields_by_name['probability_sampler'])
_TRACECONFIG.fields_by_name['probability_sampler'].containing_oneof = _TRACECONFIG.oneofs_by_name['sampler']
_TRACECONFIG.oneofs_by_name['sampler'].fields.append(
  _TRACECONFIG.fields_by_name['rate_limiting_sampler'])
_TRACECONFIG.fields_by_name['rate_limiting_sampler'].containing_oneof = _TRACECONFIG.oneofs_by_name['sampler']
_CONSTANTSAMPLER.fields_by_name['decision'].enum_type = _CONSTANTSAMPLER_CONSTANTDECISION
_CONSTANTSAMPLER_CONSTANTDECISION.containing_type = _CONSTANTSAMPLER
DESCRIPTOR.message_types_by_name['TraceConfig'] = _TRACECONFIG
DESCRIPTOR.message_types_by_name['ConstantSampler'] = _CONSTANTSAMPLER
DESCRIPTOR.message_types_by_name['ProbabilitySampler'] = _PROBABILITYSAMPLER
DESCRIPTOR.message_types_by_name['RateLimitingSampler'] = _RATELIMITINGSAMPLER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TraceConfig = _reflection.GeneratedProtocolMessageType('TraceConfig', (_message.Message,), {
  'DESCRIPTOR' : _TRACECONFIG,
  '__module__' : 'dynatrace.odin.proto.trace.v1.trace_config_pb2'
  # @@protoc_insertion_point(class_scope:dynatrace.odin.proto.trace.v1.TraceConfig)
  })
_sym_db.RegisterMessage(TraceConfig)

ConstantSampler = _reflection.GeneratedProtocolMessageType('ConstantSampler', (_message.Message,), {
  'DESCRIPTOR' : _CONSTANTSAMPLER,
  '__module__' : 'dynatrace.odin.proto.trace.v1.trace_config_pb2'
  # @@protoc_insertion_point(class_scope:dynatrace.odin.proto.trace.v1.ConstantSampler)
  })
_sym_db.RegisterMessage(ConstantSampler)

ProbabilitySampler = _reflection.GeneratedProtocolMessageType('ProbabilitySampler', (_message.Message,), {
  'DESCRIPTOR' : _PROBABILITYSAMPLER,
  '__module__' : 'dynatrace.odin.proto.trace.v1.trace_config_pb2'
  # @@protoc_insertion_point(class_scope:dynatrace.odin.proto.trace.v1.ProbabilitySampler)
  })
_sym_db.RegisterMessage(ProbabilitySampler)

RateLimitingSampler = _reflection.GeneratedProtocolMessageType('RateLimitingSampler', (_message.Message,), {
  'DESCRIPTOR' : _RATELIMITINGSAMPLER,
  '__module__' : 'dynatrace.odin.proto.trace.v1.trace_config_pb2'
  # @@protoc_insertion_point(class_scope:dynatrace.odin.proto.trace.v1.RateLimitingSampler)
  })
_sym_db.RegisterMessage(RateLimitingSampler)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
