VERSION_YEAR = 2023
VERSION_MONTH = int('01')
VERSION_DAY = int('20')
VERSION_HOUR = int('20')
VERSION_MINUTE = int('58')
MAJOR_VERSION = 0
MINOR_VERSION = 13
PATCH_VERSION = 202301202058
version_date = '2023/01/20 20:58'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
