
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-23T06:41:41-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9324c9115ce1d61d1bdd2a50f49e6a6e3f604dc9",
 "version": "0.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
