
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-24T15:21:23-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "68c17e53b76135ec4d45ecbfd9616aac89141137",
 "version": "2023.1.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
