
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-25T17:48:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef3a517c35f8d10dc76d304814ed549e59d565cc",
 "version": "0.2.1.post0.dev5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
