
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-25T09:31:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "16e3924afc2a0bef98e476ea2a3a89b4b100093a",
 "version": "0.2.0.post0.dev38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
