
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-21T21:26:26-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "86cb2f16ceca5e4dcec6f301496623c89def7169",
 "version": "7.4.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
