
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-25T17:30:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c804bba8902b8e2b56b12e846c9617352eeaf73",
 "version": "0.2.62.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
