from .geometry import Geometry as Geometry
from _typeshed import Incomplete

class LinePath:
    v: Incomplete
    tangent: Incomplete
    def __init__(self, v, tangent) -> None: ...
    def p(self, t): ...
    def dp_dt(self, t): ...

class HalfSpace(Geometry):
    normal: Incomplete
    alpha: Incomplete
    paths: Incomplete
    def __init__(self, normal, alpha: float = ...) -> None: ...
    def dist(self, x): ...
    def boundary_step(self, x): ...
