from . import pypathlib as pypathlib
from _typeshed import Incomplete

class LineSegmentPath:
    x0: Incomplete
    x1: Incomplete
    def __init__(self, x0, x1) -> None: ...
    def p(self, t): ...
    def dp_dt(self, t): ...

class Path:
    path: Incomplete
    bounding_box: Incomplete
    feature_points: Incomplete
    paths: Incomplete
    def __init__(self, points) -> None: ...
    def dist(self, x): ...
    def boundary_step(self, x): ...
