from . import pypathlib as pypathlib
from .geometry import Geometry as Geometry
from _typeshed import Incomplete

class LineSegmentPath:
    x0: Incomplete
    x1: Incomplete
    def __init__(self, x0, x1) -> None: ...
    def p(self, t): ...
    def dp_dt(self, t): ...

class Polygon(Geometry):
    polygon: Incomplete
    paths: Incomplete
    diameter: Incomplete
    def __init__(self, points) -> None: ...
    def dist(self, x): ...
    def boundary_step(self, x): ...
    def plot(self, level_set: bool = ...) -> None: ...
