# Generated by Django 4.1.5 on 2023-01-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='device',
            field=models.CharField(default='', editable=False, max_length=80),
        ),
    ]
