# Generated by Django 4.1.5 on 2023-01-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portmanager', '0006_alter_changelog_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicegroup',
            name='created',
        ),
        migrations.RemoveField(
            model_name='devicegroup',
            name='custom_field_data',
        ),
        migrations.RemoveField(
            model_name='devicegroup',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='devicegroup',
            name='tags',
        ),
    ]
