
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-19T18:20:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f32df9ac14274166e84cb95ef11e558333ca3f2c",
 "version": "0.0.5.dev20230121"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
