
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-25T10:33:47-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "04c16b055b38ad7d36fd910376a07caf4d9b12df",
 "version": "1.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
