
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-24T11:04:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "70b0dad92868285664b00a7da6a7cbd86ca31bfe",
 "version": "1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
