
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-22T22:56:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "591acda73e42b6394fdb66afb2fbe90f73bcb96b",
 "version": "0.2.61.post0.dev34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
