# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai/lzy/v1/whiteboard/whiteboard-service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.lzy.v1.whiteboard import whiteboard_pb2 as ai_dot_lzy_dot_v1_dot_whiteboard_dot_whiteboard__pb2
from ai.lzy.v1.common import data_scheme_pb2 as ai_dot_lzy_dot_v1_dot_common_dot_data__scheme__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-ai/lzy/v1/whiteboard/whiteboard-service.proto\x12\x14\x61i.lzy.v1.whiteboard\x1a%ai/lzy/v1/whiteboard/whiteboard.proto\x1a\"ai/lzy/v1/common/data-scheme.proto\"\"\n\nGetRequest\x12\x14\n\x0cwhiteboardId\x18\x01 \x01(\t\"C\n\x0bGetResponse\x12\x34\n\nwhiteboard\x18\x01 \x01(\x0b\x32 .ai.lzy.v1.whiteboard.Whiteboard\"f\n\x0bListRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04tags\x18\x02 \x03(\t\x12;\n\x11\x63reatedTimeBounds\x18\x03 \x01(\x0b\x32 .ai.lzy.v1.whiteboard.TimeBounds\"E\n\x0cListResponse\x12\x35\n\x0bwhiteboards\x18\x01 \x03(\x0b\x32 .ai.lzy.v1.whiteboard.Whiteboard\"Q\n\x19RegisterWhiteboardRequest\x12\x34\n\nwhiteboard\x18\x01 \x01(\x0b\x32 .ai.lzy.v1.whiteboard.Whiteboard\"\x1c\n\x1aRegisterWhiteboardResponse\"O\n\x17UpdateWhiteboardRequest\x12\x34\n\nwhiteboard\x18\x01 \x01(\x0b\x32 .ai.lzy.v1.whiteboard.Whiteboard\"\x1a\n\x18UpdateWhiteboardResponse2\x9d\x03\n\x14LzyWhiteboardService\x12w\n\x12RegisterWhiteboard\x12/.ai.lzy.v1.whiteboard.RegisterWhiteboardRequest\x1a\x30.ai.lzy.v1.whiteboard.RegisterWhiteboardResponse\x12q\n\x10UpdateWhiteboard\x12-.ai.lzy.v1.whiteboard.UpdateWhiteboardRequest\x1a..ai.lzy.v1.whiteboard.UpdateWhiteboardResponse\x12J\n\x03Get\x12 .ai.lzy.v1.whiteboard.GetRequest\x1a!.ai.lzy.v1.whiteboard.GetResponse\x12M\n\x04List\x12!.ai.lzy.v1.whiteboard.ListRequest\x1a\".ai.lzy.v1.whiteboard.ListResponseB\x1c\n\x14\x61i.lzy.v1.whiteboardB\x04LWBSb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.lzy.v1.whiteboard.whiteboard_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024ai.lzy.v1.whiteboardB\004LWBS'
  _GETREQUEST._serialized_start=146
  _GETREQUEST._serialized_end=180
  _GETRESPONSE._serialized_start=182
  _GETRESPONSE._serialized_end=249
  _LISTREQUEST._serialized_start=251
  _LISTREQUEST._serialized_end=353
  _LISTRESPONSE._serialized_start=355
  _LISTRESPONSE._serialized_end=424
  _REGISTERWHITEBOARDREQUEST._serialized_start=426
  _REGISTERWHITEBOARDREQUEST._serialized_end=507
  _REGISTERWHITEBOARDRESPONSE._serialized_start=509
  _REGISTERWHITEBOARDRESPONSE._serialized_end=537
  _UPDATEWHITEBOARDREQUEST._serialized_start=539
  _UPDATEWHITEBOARDREQUEST._serialized_end=618
  _UPDATEWHITEBOARDRESPONSE._serialized_start=620
  _UPDATEWHITEBOARDRESPONSE._serialized_end=646
  _LZYWHITEBOARDSERVICE._serialized_start=649
  _LZYWHITEBOARDSERVICE._serialized_end=1062
# @@protoc_insertion_point(module_scope)
