
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-20T03:31:37-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9bdf71fe896a22d79b63adc8a53f1b22fc43672b",
 "version": "4.7.46"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
