
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-20T13:58:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b5eec6e704eb01eb64c3a83cafc9b74cff210c9",
 "version": "1.3.7rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
