VERSION_YEAR = 2023
VERSION_MONTH = int('01')
VERSION_DAY = int('24')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('42')
MAJOR_VERSION = 1
MINOR_VERSION = 9
PATCH_VERSION = 202301241142
version_date = '2023/01/24 11:42'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
