"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _error_types:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _error_typesEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_error_types.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ft_Error: _error_types.ValueType  # 0
    ft_DeviceError: _error_types.ValueType  # 1
    ft_ProtocolError: _error_types.ValueType  # 2
    out_of_range: _error_types.ValueType  # 3
    unknown_error: _error_types.ValueType  # 4
    contention_timeout: _error_types.ValueType  # 5
    ft_ServerError: _error_types.ValueType  # 6
    ft_AuthError: _error_types.ValueType  # 7

class error_types(_error_types, metaclass=_error_typesEnumTypeWrapper): ...

ft_Error: error_types.ValueType  # 0
ft_DeviceError: error_types.ValueType  # 1
ft_ProtocolError: error_types.ValueType  # 2
out_of_range: error_types.ValueType  # 3
unknown_error: error_types.ValueType  # 4
contention_timeout: error_types.ValueType  # 5
ft_ServerError: error_types.ValueType  # 6
ft_AuthError: error_types.ValueType  # 7
global___error_types = error_types

@typing_extensions.final
class errstatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TP_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    tp: global___error_types.ValueType
    msg: builtins.str
    def __init__(
        self,
        *,
        tp: global___error_types.ValueType = ...,
        msg: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["msg", b"msg", "tp", b"tp"]) -> None: ...

global___errstatus = errstatus
