"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ft_flags_pb2
import ft_types_pb2
import grpc

class flagsStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    SetServerFlag: grpc.UnaryUnaryMultiCallable[
        ft_flags_pb2.serverflag,
        ft_flags_pb2.serverflag,
    ]
    GetServerFlag: grpc.UnaryUnaryMultiCallable[
        ft_flags_pb2.serverflag,
        ft_flags_pb2.serverflag,
    ]
    ListServerFlags: grpc.UnaryUnaryMultiCallable[
        ft_types_pb2.empty,
        ft_flags_pb2.serverflaglist,
    ]
    DropServerFlag: grpc.UnaryUnaryMultiCallable[
        ft_flags_pb2.serverflag,
        ft_flags_pb2.serverflag,
    ]

class flagsServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def SetServerFlag(
        self,
        request: ft_flags_pb2.serverflag,
        context: grpc.ServicerContext,
    ) -> ft_flags_pb2.serverflag: ...
    @abc.abstractmethod
    def GetServerFlag(
        self,
        request: ft_flags_pb2.serverflag,
        context: grpc.ServicerContext,
    ) -> ft_flags_pb2.serverflag: ...
    @abc.abstractmethod
    def ListServerFlags(
        self,
        request: ft_types_pb2.empty,
        context: grpc.ServicerContext,
    ) -> ft_flags_pb2.serverflaglist: ...
    @abc.abstractmethod
    def DropServerFlag(
        self,
        request: ft_flags_pb2.serverflag,
        context: grpc.ServicerContext,
    ) -> ft_flags_pb2.serverflag: ...

def add_flagsServicer_to_server(servicer: flagsServicer, server: grpc.Server) -> None: ...
