
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-23T14:13:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7d2f1245d0741a0e7d8c3dce7012d4410fafc56",
 "version": "1.13.168"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
