
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-25T09:05:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd282e9d0a7cc2bcf987537fa33c806c2e2c3938",
 "version": "0.2.0.post0.dev26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
