
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-23T21:11:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "591f3db950580d6e3cea3104a993c41e1e8a4544",
 "version": "1.2.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
