# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-parallel-utils',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-parallel-utils',
                'lib_path': 'cjm_parallel_utils'},
  'syms': { 'cjm_parallel_utils.core': {'cjm_parallel_utils.core.parallel': ('core.html#parallel', 'cjm_parallel_utils/core.py')},
            'cjm_parallel_utils.parallel_utils': { 'cjm_parallel_utils.parallel_utils.parallel': ( 'core.html#parallel',
                                                                                                   'cjm_parallel_utils/parallel_utils.py')}}}
