
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-25T18:42:01+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "83f65019a0c75e40fec944954bd02e6e18e8561d",
 "version": "0.2.62.post0.dev8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
