
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-20T22:35:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7fe0986b817ff22fd15bc6368c26a9b153de75dd",
 "version": "v3.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
