
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-23T19:29:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3b4b2302d2b02387f32f980c17ca66a48bf53fb",
 "version": "0.0.5.dev20230125"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
