
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-05T23:36:10-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "7890228715320c2d1ff6989ff522829b5d6411ba",
 "version": "0.1.0.dev20230121"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
