
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-24T18:58:02-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c95bf85f90da2ef99a9e35e00238af6b04ae6687",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
