import numpy as np
from typing import Callable

def multi_newton(x0: np.ndarray, is_inside: Callable, boundary_step: Callable, tol: float, max_num_steps: int = ...) -> np.ndarray: ...
def show(pts, cells, geo, title: Union[str, None] = ..., full_screen: bool = ...): ...
def find_feature_points(geometries, num_steps: int = ...): ...
def unique_float_cols(data: np.ndarray, k: int = ..., tol: float = ...): ...
