
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-24T14:39:56-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8036da3d7a11d5997ef05e40468944b3513a141b",
 "version": "0.2.61.post0.dev44"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
