from .helpers import shoelace as shoelace
from .path import Path as Path
from _typeshed import Incomplete

class ClosedPath(Path):
    area: Incomplete
    positive_orientation: Incomplete
    def __init__(self, points) -> None: ...
    def signed_squared_distance(self, x): ...
    def signed_distance(self, x): ...
    def contains_points(self, x, tol: float = ...): ...
    @property
    def is_convex_node(self): ...
