from _typeshed import Incomplete

class Path:
    points: Incomplete
    edges: Incomplete
    e_dot_e: Incomplete
    def __init__(self, points) -> None: ...
    @property
    def diameter(self): ...
    def squared_distance(self, x): ...
    def distance(self, x): ...
    def closest_points(self, x): ...
    def plot(self, color: str = ...) -> None: ...
    def show(self, *args, **kwargs) -> None: ...
