class User:
    def __init__(self, user_data: dict):
        self.last_name: str = user_data.get('lastName')
        self.usdc_receiving_wallet: str = user_data.get('usdcReceivingWallet')
        self.email: str = user_data.get('email')
        self.country: str = user_data.get('country')
        self.first_name: str = user_data.get('firstName')
        self.user_sub: str = user_data.get('userSub')
        self.city: str = user_data.get('city')
        self.default_payment_method: str = user_data.get('defaultPaymentMethod')
        self.num_id: int = user_data.get('numId')
        self.aml_status: str = user_data.get('amlStatus')
        self.algo_token_wallet: str = user_data.get('algoTokenWallet')
        self.id: str = user_data.get('id')
        self.verification_status: str = user_data.get('verificationStatus')
        self.postal_code: str = user_data.get('postalCode')
        self.address_state: str = user_data.get('addressState')
        self.stripe_customer_id: str = user_data.get('stripeCustomerId')
        self.accepted_disclaimer: int = user_data.get('acceptedDisclaimer')
        self.created_at: int = user_data.get('createdAt')
        self.governance_survey_completed_on: int = user_data.get('governanceSurveyCompletedOn')
        self.referred_by: str = user_data.get('referredBy')
        self.shared_wallet_address: str = user_data.get('sharedWalletAddress')
        self.street_address: str = user_data.get('streetAddress')
        self.updated_at: int = user_data.get('updatedAt')
        self.verification_intents: int = user_data.get('verificationIntents')
        self.referral_id: str = user_data.get('referralId')
        self.algo_receiving_wallet: str = user_data.get('algoReceivingWallet')
        self.identity_status: str = user_data.get('identityStatus')


