
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-23T23:17:51+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5eb1d23a95bbe6c800af5f471e7a1163f6c349e3",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
