
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-25T12:53:00-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "19610b8ddb1cc69a2adbb98e3c5d5fe879dca27f",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
