from sparknlp_jsl.legal.graph.relation_extraction.relation_extraction_dl import RelationExtractionDLModel
from sparknlp_jsl.legal.graph.relation_extraction.zero_shot_relation_extraction import \
    ZeroShotRelationExtractionModel
