
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-24T13:26:10-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6fb212584fdb8ff24a7955e6e50d2244c5d92a65",
 "version": "4.7.47"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
