
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-23T09:27:57-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "563820ab6284c47c590469a960ca7cb2e789362f",
 "version": "1.18.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
